name: Chisel-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Cache verilator
        id: cache-verilator
        uses: actions/cache@v2
        with:
          path: |
            ~/verilator-4.210
            ~/tools/verilator
          key: ${{ runner.os }}-verilator

      - name: Build and Install Verilator
        if: steps.cache-verilator.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install git perl python3 make autoconf g++ flex bison ccache
          sudo apt-get install libfl2 libfl-dev
          sudo apt-get install zlibc zlib1g zlib1g-dev
          wget https://github.com/verilator/verilator/archive/refs/tags/v4.210.tar.gz
          tar xf v4.210.tar.gz
          cd verilator-4.210
          autoconf
          ./configure --prefix=/home/runner/tools/verilator
          make -j 2
          make install

      - name: Cache WLA DX
        id: cache-wla-dx
        uses: actions/cache@v2
        with:
          path: |
            ~/wla-dx
            ~/tools/wla-dx
          key: ${{ runner.os }}-wla-dx

      - name: Build and Install WLA DX
        if: steps.cache-wla-dx.outputs.cache-hit != 'true'
        run: |
          sudo apt install cmake
          git clone https://github.com/vhelin/wla-dx
          cd wla-dx
          git checkout -b v10.0 refs/tags/v10.0
          mkdir build && cd build # Create building directory
          cmake .. -DCMAKE_INSTALL_PREFIX=/home/runner/tools/wla-dx
          cmake --build . --config Release
          cmake -P cmake_install.cmake

      - name: Install sbt
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt-get update
          sudo apt-get install sbt

      - name: Run test
        run: |
           sudo apt-get ccache
           export PATH=/home/runner/tools/verilator/bin:/home/runner/tools/wla-dx/bin:$PATH
           echo "DUMMY RUN"
           sbt "compile"
           sbt "convertBin2Hex"
           sbt "testOnly CpuTest"