name: Chisel-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Cache verilator
        id: cache-verilator
        uses: actions/cache@v2
        with:
          path: |
            ~/ccache
            ~/verilator-4.210
            ~/tools/ccache
            ~/tools/verilator
          key: ${{ runner.os }}-verilator

      - name: Build and Install Verilator
        if: steps.cache-verilator.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -no-install-recommends -y \
          autoconf \
          bc \
          bison \
          build-essential \
          ca-certificates \
          ccache \
          clang \
          cmake \
          flex \
          gdb \
          git \
          gtkwave \
          help2man \
          libfl2 \
          libfl-dev \
          libgoogle-perftools-dev \
          libsystemc \
          libsystemc-dev \
          numactl \
          perl \
          python3 \
          wget \
          zlibc \
          zlib1g \
          zlib1g-dev
          git clone https://github.com/verilator/verilator.git
          cd verilator
          git checkout -b v4.210 refs/tags/v4.210
          autoconf
          ./configure --prefix=/home/runner/tools/verilator
          make -j 3
          make install

      - name: Cache WLA DX
        id: cache-wla-dx
        uses: actions/cache@v2
        with:
          path: |
            ~/wla-dx
            ~/tools/wla-dx
          key: ${{ runner.os }}-wla-dx

      - name: Build and Install WLA DX
        if: steps.cache-wla-dx.outputs.cache-hit != 'true'
        run: |
          sudo apt install cmake
          git clone https://github.com/vhelin/wla-dx
          cd wla-dx
          git checkout -b v10.0 refs/tags/v10.0
          mkdir build && cd build # Create building directory
          cmake .. -DCMAKE_INSTALL_PREFIX=/home/runner/tools/wla-dx
          cmake --build . --config Release
          cmake -P cmake_install.cmake

      - name: Cache sbt
        id: cache-sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/sbt-1.5.5.tgz
            ~/tools/sbt
          key: ${{ runner.os }}-sbt

      - name: Install sbt
        if: steps.cache-sbt.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.tgz
          tar xf sbt-1.5.5.tgz
          mv sbt tools

      - name: Cache test data
        id: cache-test-data
        uses: actions/cache@v2
        with:
          path: |
            ~/work/chisel-dmg/chisel-dmg/src/test/resources/cpu/*.gb.hex*
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.s') }}

      - name: Build test data
        if: steps.cache-test-data.outputs.cache-hit != 'true'
        run: |
           export PATH=/home/runner/tools/sbt/bin:/home/runner/tools/wla-dx/bin:$PATH
           sbt "convertBin2Hex"

      - name: Run test
        run: |
           export PATH=/home/runner/tools/sbt/bin:/home/runner/tools/ccache/bin:/home/runner/tools/verilator/bin:/home/runner/tools/wla-dx/bin:$PATH
           sbt "testOnly CpuTest -- -P2"