name: Chisel-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Cache verilator
        id: cache-verilator
        uses: actions/cache@v2
        with:
          path: |
            ~/verilator-4.210
            ~/verilator/
          key: ${{ runner.os }}-verilator

      - name: Install Verilator Dependancy
        if: steps.cache-verilator-dependancy.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install git perl python3 make autoconf g++ flex bison ccache
          sudo apt-get install libfl2 libfl-dev
          sudo apt-get install zlibc zlib1g zlib1g-dev

      - name: Build verilator
        if: steps.cache-verilator.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/verilator/verilator/archive/refs/tags/v4.210.tar.gz
          tar xf v4.210.tar.gz
          cd verilator-4.210
          autoconf
          ./configure --prefix=/home/runner/tools
          make -j 2
          make install
          export PATH=/home/runner/tools/bin:$PATH
          verilator --version

      - name: Install sbt
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt-get update
          sudo apt-get install sbt

      - name: Run test
        run:
           echo "DUMMY RUN"
#          sbt "testOnly CpuTest"